[package]
name = "backend"
version = "0.0.0"
edition = "2024"

[dependencies]
common = { path = "../common" }
crossbeam = "0.8.4"
dashmap = "6.1.0"
num_cpus = "1.17.0"
rand = "0.9.1"
rayon = "1.10.0"
regex = "1.11.1"
thread_local = "1.1.9"

[dev-dependencies]
strsim = "0.11.1"
