[package]
name = "common"
version = "0.0.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
csv = "1.3.1"
num-traits = "0.2.19"
rayon = "1.10.0"
serde = { version = "1.0.219", features = ["derive"] }
sysinfo = "0.35.2"
